import Head from 'next/head'
import { useState } from 'react'

import Markdown from '../components/Markdown'
import DocumentHeader from '../components/DocumentHeader'
import Footer from '../components/Footer'

import { INITIAL_DATA } from '../utils';

import styles from '../styles/Home.module.css'

export default function Home() {
  const [header, setHeader] = useState(INITIAL_DATA)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <strong>Markdown File Generator</strong>
        </h1>
        <DocumentHeader handleHeader={setHeader} header={header} />
        <Markdown header={header} />
      </main>
      <Footer />
    </div>
  )
}
