import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

import Markdown from '../components/Markdown'
import DocumentHeader from '../components/DocumentHeader'

import { INITIAL_DATA } from '../utils';

import styles from '../styles/Home.module.css'

export default function Home() {
  const [header, setHeader] = useState(INITIAL_DATA)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <strong>Markdown File Generator</strong>
        </h1>
        <DocumentHeader handleHeader={setHeader} header={header} />
        <Markdown header={header} />
      </main>

      <footer className={styles.footer} id="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
